### ISSUE TITLE
#1 Dune平台简介有张截图语法会有错误

### ISSUE THREAD

**Issue by difengJ** [SixdegreeLab/MasteringChainAnalytics#58]
https://sixdegreelab.gitbook.io/mastering-chain-analytics/ru-men-jiao-cheng/dune#he-xin-gong-neng
在**参数**这里，写12 months会报错，建议SQL可以 interval '{{datetime}}' month
<img width="1065" alt="Screenshot 2023-05-04 at 22 03 29" src="https://user-images.githubusercontent.com/19460327/236232454-bd4d52cd-6dc6-49d9-9bde-81f5597e4b85.png">

**Comment by 0xbitfly** [comment]
这个是因为版本不一样导致的，截图里用的sparkSQL，感谢指出，我们修改一下截图
