### ISSUE TITLE
跳转链接错误

### ISSUE THREAD

**Issue by Oaciqihz** [SixdegreeLab/MasteringChainAnalytics#59]
### gitbook
![image](https://github.com/SixdegreeLab/MasteringChainAnalytics/assets/108737430/734e0c33-830e-47c7-b9a5-70f0003d6673)

### 点击后跳转结果
![image](https://github.com/SixdegreeLab/MasteringChainAnalytics/assets/108737430/2128aa89-d711-4bed-bf75-663cfddf1ffa)

### 错误位置
应修改为: `(../02_get_started/readme.md)`
![image](https://github.com/SixdegreeLab/MasteringChainAnalytics/assets/108737430/cb90a003-e6c4-4b8f-91fe-3c667a87f143)

**Comment by springzh** [comment]
感谢反馈！已修复。
